name: Deploy SAM WebSocket API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Node.js (for esbuild)
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Setup SAM CLI
      run: pip install aws-sam-cli

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Install dependencies
      run: npm i
    
    - name: Install esbuild
      run: npm install -g esbuild

    - name: Build SAM App
      run: sam build

    - name: Deploy SAM App
      run: |
        sam deploy \
          --stack-name ${{ secrets.STACK_NAME }} \
          --region us-east-1 \
          --capabilities CAPABILITY_IAM \
          --no-confirm-changeset \
          --no-fail-on-empty-changeset
